"""Add a LLM response hash to job description

Revision ID: 22a3f3f4fafc
Revises: ee057125bb9a
Create Date: 2026-04-11 11:38:47.679040

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22a3f3f4fafc"
down_revision: Union[str, Sequence[str], None] = "ee057125bb9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prompt_hash", sa.String(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("response_hash", sa.String(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("llm_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_llm_cache_prompt_hash"),
        "llm_cache",
        ["prompt_hash"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_llm_cache_response_hash"),
        "llm_cache",
        ["response_hash"],
        unique=False,
        if_not_exists=True,
    )
    op.add_column(
        "job_descriptions_parsed", sa.Column("input_hash", sa.String(), nullable=True)
    )
    op.add_column(
        "job_descriptions_parsed", sa.Column("full_response", sa.Text(), nullable=True)
    )
    op.create_index(
        op.f("ix_job_descriptions_parsed_input_hash"),
        "job_descriptions_parsed",
        ["input_hash"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job_descriptions_parsed_input_hash"),
        table_name="job_descriptions_parsed",
    )
    op.drop_column("job_descriptions_parsed", "full_response")
    op.drop_column("job_descriptions_parsed", "input_hash")
    op.drop_index(op.f("ix_llm_cache_response_hash"), table_name="llm_cache")
    op.drop_index(op.f("ix_llm_cache_prompt_hash"), table_name="llm_cache")
    op.drop_table("llm_cache")
    # ### end Alembic commands ###
