"""Job Description Tables

Revision ID: 7efea4601644
Revises: ed5e7ea47bd0
Create Date: 2026-03-19 21:29:21.796088

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7efea4601644"
down_revision: Union[str, Sequence[str], None] = "ed5e7ea47bd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_descriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("raw_text", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "job_descriptions_parsed",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_description_id", sa.Integer(), nullable=True),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("required_skills", sa.String(), nullable=False),
        sa.Column("prefered_skills", sa.String(), nullable=False),
        sa.Column("keywords", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_description_id"],
            ["job_descriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "star_metadatas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("subtitle", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "star_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metadata_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("situation", sa.String(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metadata_id"],
            ["star_metadatas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "star_entries_skills_assoc",
        sa.Column("star_entry_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["star_entry_id"],
            ["star_entries.id"],
        ),
        sa.PrimaryKeyConstraint("star_entry_id", "skill_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("star_entries_skills_assoc")
    op.drop_table("star_entries")
    op.drop_table("star_metadatas")
    op.drop_table("job_descriptions_parsed")
    op.drop_table("users")
    op.drop_table("skills")
    op.drop_table("job_descriptions")
    # ### end Alembic commands ###
