"""Add Input and Full text to resume

Revision ID: 8d188f5554a9
Revises: f9c231e5e71e
Create Date: 2026-05-09 20:37:42.682107

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d188f5554a9"
down_revision: Union[str, Sequence[str], None] = "f9c231e5e71e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job_descriptions",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "job_descriptions_parsed",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "llm_cache", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.add_column("resumes", sa.Column("input_hash", sa.String(), nullable=True))
    op.add_column("resumes", sa.Column("full_response", sa.Text(), nullable=True))
    op.alter_column(
        "resumes", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.create_index(
        op.f("ix_resumes_input_hash"), "resumes", ["input_hash"], unique=False
    )
    op.alter_column(
        "star_entries",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "star_metadatas",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "users", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "star_metadatas",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "star_entries",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_resumes_input_hash"), table_name="resumes")
    op.alter_column(
        "resumes", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.drop_column("resumes", "full_response")
    op.drop_column("resumes", "input_hash")
    op.alter_column(
        "llm_cache",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "job_descriptions_parsed",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "job_descriptions",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
