"""Create star_entry table

Revision ID: ed5e7ea47bd0
Revises: 5ad99ecc41ab
Create Date: 2026-03-15 20:31:36.255431

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed5e7ea47bd0"
down_revision: Union[str, Sequence[str], None] = "5ad99ecc41ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "star_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metadata_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("situation", sa.String(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metadata_id"],
            ["star_metadatas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "star_entries_skills_assoc",
        sa.Column("star_entry_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["star_entry_id"],
            ["star_entries.id"],
        ),
        sa.PrimaryKeyConstraint("star_entry_id", "skill_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("star_entries_skills_assoc")
    op.drop_table("star_entries")
    op.drop_table("skills")
    # ### end Alembic commands ###
