"""Resume and Matches Tables

Revision ID: ee057125bb9a
Revises: 7efea4601644
Create Date: 2026-03-19 21:51:27.704715

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee057125bb9a"
down_revision: Union[str, Sequence[str], None] = "7efea4601644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("raw_text", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matches",
        sa.Column("resume_id", sa.Integer(), nullable=False),
        sa.Column("job_description_parsed_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("llm_analysis", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_description_parsed_id"],
            ["job_descriptions_parsed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.PrimaryKeyConstraint("resume_id", "job_description_parsed_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    op.drop_table("resumes")
    # ### end Alembic commands ###
