[loggers]
keys=root,src

[handlers]
keys=null

[formatters]
keys=standard

[logger_root]
level=CRITICAL
handlers=null

[logger_src]
level=CRITICAL
handlers=null
qualname=src
propagate=0

[logger_src.core]
level=CRITICAL
handlers=null
qualname=src.core
propagate=0

[logger_src.scrapers]
level=CRITICAL
handlers=null
qualname=src.scrapers
propagate=0

[handler_null]
class=NullHandler
level=CRITICAL

[formatter_standard]
format=%(name)s - %(levelname)s - %(message)s
